spring:
  application:
    name: simple-posts-board
  datasource:
    url: jdbc:h2:~/simple-posts-board;AUTO_SERVER=TRUE
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop

logging:
  level:
    org.springframework.jdbc.core: debug
    org.hibernate.SQL: debug
